apiVersion: v1
kind: Pod
metadata:
  name: gpemu-test
spec:
  restartPolicy: OnFailure
  schedulerName: my-scheduler
  containers:
  - image: alpine
    name: gpemu-test-ctr
    command:
    - sh
    - -c
    - |
      ls /edev
      sleep 1000000
